### ISSUE TITLE
fatInitDefault() hangs CPU

### ISSUE THREAD

**Issue by HTV04** [extremscorner/libogc2#15]
For some reason, libogc2's libfat has a problem with `fatInitDefault()`. Whenever it is called, the CPU will hang. I can't seem to find out why this is happening, but the behavior is consistent. I only encountered this issue with libogc2 for the Wii, so I can't say for sure whether it also occurs on the GameCube.

**Comment by HTV04** [comment]
Seems to have been fixed in 1a55bfffbbc1614e719a4bb2448a46123ca170c6

**Comment by HTV04** [comment]
Yeah, I was encountering this issue in Dolphin, so I shouldn't have assumed this also occurred on real hardware. Sorry about that.

The latest commit seems to have fixed the issue in Dolphin, though. Any reason those those two commits were reverted for real hardware?

**Comment by Extrems** [comment]
Some third-party GameCube Memory Cards misbehaved and the fix wasn't perfect, so it was finally decided to go back.

**Comment by HTV04** [comment]
Oh, okay. Well, for the sake of developing with Dolphin, I'm glad libogc2 works on it again :)

**Comment by Extrems** [comment]
Technically Dolphin is still failing when compiling for GameCube, as it fails to complete the EXI transfers on Serial Port 2.

**Comment by Extrems** [comment]
Also the recent changes to put the SD Card back into idle mode upon exit are partly what allowed this.

**Comment by HTV04** [comment]
> Technically Dolphin is still failing when compiling for GameCube, as it fails to complete the EXI transfers on Serial Port 2.

Interesting. If I can find a workaround or mitigation for this issue on the libogc side of things, I'll create a PR for libogc2, if you're interested.

**Comment by Extrems** [comment]
Sure. By detecting Dolphin. Which is trivial, but not something we should need to do.

**Comment by HTV04** [comment]
> Sure. By detecting Dolphin. Which is trivial, but not something we should need to do.

We could, but I feel like that would be a bad idea because Dolphin shouldn't be considered a "special case," it should be expected to function like a normal Wii or Gamecube.

I updated my previous comment with this: "(i.e. functions to avoid or use instead)"

**Comment by HTV04** [comment]
> Well, Dolphin currently doesn't emulate any supported storage devices, so you can simply avoid fatInitDefault entirely.

Oh, well that explains things. I was thinking libogc2 itself just crashed on Dolphin emulating the GameCube for a second.

> This should all be solved once https://github.com/Pokechu22/dolphin/tree/sd-gecko is merged.

Yay, someone's working on SD Gecko support! It's about time, that would be a huge step for GameCube homebrew support. Looking forward to it getting merged upstream.
